name: tests

on:
  push:
    paths-ignore:
      - 'LICENSE-*'
      - '**.md'
  pull_request:
    paths-ignore:
      - 'LICENSE-*'
      - '**.md'

jobs:
  linters:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Cargo fmt
        run: cargo fmt --check

      - name: Cargo clippy
        run: cargo clippy -- -D warnings

  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        channel: [ stable ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Rust ${{ matrix.channel }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.channel }}

      - name: Run tests
        run: cargo test --verbose
